#!/usr/bin/env bash

# Bash script that displays the content of the file /etc/passwd
	#username
	# user id
	# Home directory path for the user


# sudo cat /etc/passwd | cut -f1,3,6 -d':'
while read -r line && true;

# cut -d: -f 1,3,6 < /etc/passwd | while read -r line
do

# sudo cat /etc/passwd | cut -f1,3,6 -d':'

	echo "$line" | cut -f1,4,7 -d':'

done < /etc/passwd

