#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS


while IFS=":" read -r username password id gid userid_info home_dir command

do
	echo "The user $username is part of the $gid gang, lives in $home_dir and rides $command. $id's place is protected by the passcode $password, more info about the user here: $userid_info"

done < /etc/passwd



