#!/usr/bin/env bash
#Bash script that displays the visitor IP along with the HTTP status code from the Apache log file
#This script display the visitor ip address and http status code

awk '{print $1,$9}' apache-access.log
