#!/usr/bin/env bash
# Bash script that displays Best School 10 times using while loop.
# This script is displaying "Best School" 10 times


index_count=0

while [ $index_count -le 9 ]
do
	echo "Best School"
	(( index_count++ ))
done

