#!/usr/bin/env bash
# Bash script that displays Best School 10 times using until loop.
# This script is displaying "Best School" 10 times


index_count=0

until [ $index_count -gt 9 ]
do
	echo "Best School"
	(( index_count++ ))
done

