#!/usr/bin/env bash
# Bash script that displays Best School 10 times using while loop.
# This script is displaying "Best School" 10 times


index_count=0

while [ $index_count -le 9 ]
do
	if [ $index_count -eq 3 ]
	then
		echo -e "bad luck"
	elif [ $index_count -eq 7 ]
	then
		echo -e "good luck"
	else
		echo "Best School"
	fi
	(( index_count++ ))
done

