#!/usr/bin/env bash
# Bash script that displays:
	# The content of the current directory
	#In a list format
	# Where only the part of the name after the first dash is displayed (refer to the example)
# This script is displaying the content of the current directory.


list="$(ls)"
for item in $list
do
	echo "$item" | cut -d "-" -f 2

done

