#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on

ifconfig | grep 'inet addr' | cut -f2 -d':' | cut -f1 -d' '

#ifconfig | grep -o -P '(?<=inet addr:).*?(?=\s)'
